# based on https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/master/binder/environment.yml
name: burnman-binder-demos

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<=3.14
  - jupyterlab >=3,<=4.4.9
  - pip
  - ipympl
  - ipywidgets
  - appmode
  - pip:
    - mpl-interactions
    - pycddlib-standalone
    - cvxpy
    - jupyter
